services:
  backend:
    build: ./bussola_api
    container_name: bussola_backend
    env_file:
      - ./bussola_api/.env
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./bussola_api/data:/app/data
    restart: unless-stopped
    networks:
      - coolify

  frontend:
    build: ./bussola_web
    container_name: bussola_frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - coolify

networks:
  coolify:
    external: true
