"""add metas e movimentacao_meta

Revision ID: 1e66514e74ae
Revises: 4526ad6eee2c
Create Date: 2026-07-19 20:43:58.160367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e66514e74ae'
down_revision: Union[str, Sequence[str], None] = '4526ad6eee2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('valor_alvo', sa.Float(), nullable=False),
    sa.Column('saldo_atual', sa.Float(), nullable=False),
    sa.Column('data_alvo', sa.Date(), nullable=True),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.Column('imagem_url', sa.String(length=500), nullable=True),
    sa.Column('trancada', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('aporte_mensal_valor', sa.Float(), nullable=True),
    sa.Column('aporte_mensal_dia', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('concluida_em', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacao_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('id_grupo_recorrencia', sa.String(length=100), nullable=True),
    sa.Column('observacao', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['meta_id'], ['meta.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacao_meta_meta_id'), 'movimentacao_meta', ['meta_id'], unique=False)
    op.create_index(op.f('ix_movimentacao_meta_id_grupo_recorrencia'), 'movimentacao_meta', ['id_grupo_recorrencia'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimentacao_meta_id_grupo_recorrencia'), table_name='movimentacao_meta')
    op.drop_index(op.f('ix_movimentacao_meta_meta_id'), table_name='movimentacao_meta')
    op.drop_table('movimentacao_meta')
    op.drop_table('meta')
    # ### end Alembic commands ###
