"""Add Ritmo Module

Revision ID: 220a3a0dea0a
Revises: 
Create Date: 2025-12-17 10:54:19.210640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220a3a0dea0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('meta_limite', sa.Float(), nullable=False),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compromisso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('local', sa.String(length=200), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('lembrete', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compromisso_id'), 'compromisso', ['id'], unique=False)
    op.create_table('grupo_anotacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_grupo_anotacao_id'), 'grupo_anotacao', ['id'], unique=False)
    op.create_table('segredo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('servico', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.Column('data_expiracao', sa.Date(), nullable=True),
    sa.Column('_valor_criptografado', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segredo_id'), 'segredo', ['id'], unique=False)
    op.create_table('tarefa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('prazo', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('fixado', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarefa_id'), 'tarefa', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('anotacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('fixado', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo_anotacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anotacao_id'), 'anotacao', ['id'], unique=False)
    op.create_table('historico_gasto_mensal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_gasto', sa.Float(), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_gasto_mensal_data_referencia'), 'historico_gasto_mensal', ['data_referencia'], unique=False)
    op.create_table('ritmo_bio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('bf_estimado', sa.Float(), nullable=True),
    sa.Column('nivel_atividade', sa.String(), nullable=True),
    sa.Column('objetivo', sa.String(), nullable=True),
    sa.Column('tmb', sa.Float(), nullable=True),
    sa.Column('gasto_calorico_total', sa.Float(), nullable=True),
    sa.Column('meta_proteina', sa.Float(), nullable=True),
    sa.Column('meta_carbo', sa.Float(), nullable=True),
    sa.Column('meta_gordura', sa.Float(), nullable=True),
    sa.Column('meta_agua', sa.Float(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ritmo_bio_id'), 'ritmo_bio', ['id'], unique=False)
    op.create_table('ritmo_dieta_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('calorias_calculadas', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ritmo_dieta_config_id'), 'ritmo_dieta_config', ['id'], unique=False)
    op.create_table('ritmo_plano_treino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ritmo_plano_treino_id'), 'ritmo_plano_treino', ['id'], unique=False)
    op.create_table('subtarefa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=True),
    sa.Column('tarefa_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['subtarefa.id'], ),
    sa.ForeignKeyConstraint(['tarefa_id'], ['tarefa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtarefa_id'), 'subtarefa', ['id'], unique=False)
    op.create_table('transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('tipo_recorrencia', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('parcela_atual', sa.Integer(), nullable=True),
    sa.Column('total_parcelas', sa.Integer(), nullable=True),
    sa.Column('frequencia', sa.String(length=50), nullable=True),
    sa.Column('id_grupo_recorrencia', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacao_id_grupo_recorrencia'), 'transacao', ['id_grupo_recorrencia'], unique=False)
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('anotacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anotacao_id'], ['anotacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_id'), 'link', ['id'], unique=False)
    op.create_table('ritmo_dia_treino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plano_id'], ['ritmo_plano_treino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ritmo_dia_treino_id'), 'ritmo_dia_treino', ['id'], unique=False)
    op.create_table('ritmo_refeicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dieta_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('horario', sa.String(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dieta_id'], ['ritmo_dieta_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ritmo_refeicao_id'), 'ritmo_refeicao', ['id'], unique=False)
    op.create_table('ritmo_alimento_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refeicao_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('unidade', sa.String(), nullable=True),
    sa.Column('calorias', sa.Float(), nullable=True),
    sa.Column('proteina', sa.Float(), nullable=True),
    sa.Column('carbo', sa.Float(), nullable=True),
    sa.Column('gordura', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['refeicao_id'], ['ritmo_refeicao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ritmo_alimento_item_id'), 'ritmo_alimento_item', ['id'], unique=False)
    op.create_table('ritmo_exercicio_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_treino_id', sa.Integer(), nullable=True),
    sa.Column('nome_exercicio', sa.String(), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('grupo_muscular', sa.String(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('repeticoes_min', sa.Integer(), nullable=True),
    sa.Column('repeticoes_max', sa.Integer(), nullable=True),
    sa.Column('carga_prevista', sa.Float(), nullable=True),
    sa.Column('descanso_segundos', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dia_treino_id'], ['ritmo_dia_treino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ritmo_exercicio_item_id'), 'ritmo_exercicio_item', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ritmo_exercicio_item_id'), table_name='ritmo_exercicio_item')
    op.drop_table('ritmo_exercicio_item')
    op.drop_index(op.f('ix_ritmo_alimento_item_id'), table_name='ritmo_alimento_item')
    op.drop_table('ritmo_alimento_item')
    op.drop_index(op.f('ix_ritmo_refeicao_id'), table_name='ritmo_refeicao')
    op.drop_table('ritmo_refeicao')
    op.drop_index(op.f('ix_ritmo_dia_treino_id'), table_name='ritmo_dia_treino')
    op.drop_table('ritmo_dia_treino')
    op.drop_index(op.f('ix_link_id'), table_name='link')
    op.drop_table('link')
    op.drop_index(op.f('ix_transacao_id_grupo_recorrencia'), table_name='transacao')
    op.drop_table('transacao')
    op.drop_index(op.f('ix_subtarefa_id'), table_name='subtarefa')
    op.drop_table('subtarefa')
    op.drop_index(op.f('ix_ritmo_plano_treino_id'), table_name='ritmo_plano_treino')
    op.drop_table('ritmo_plano_treino')
    op.drop_index(op.f('ix_ritmo_dieta_config_id'), table_name='ritmo_dieta_config')
    op.drop_table('ritmo_dieta_config')
    op.drop_index(op.f('ix_ritmo_bio_id'), table_name='ritmo_bio')
    op.drop_table('ritmo_bio')
    op.drop_index(op.f('ix_historico_gasto_mensal_data_referencia'), table_name='historico_gasto_mensal')
    op.drop_table('historico_gasto_mensal')
    op.drop_index(op.f('ix_anotacao_id'), table_name='anotacao')
    op.drop_table('anotacao')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tarefa_id'), table_name='tarefa')
    op.drop_table('tarefa')
    op.drop_index(op.f('ix_segredo_id'), table_name='segredo')
    op.drop_table('segredo')
    op.drop_index(op.f('ix_grupo_anotacao_id'), table_name='grupo_anotacao')
    op.drop_table('grupo_anotacao')
    op.drop_index(op.f('ix_compromisso_id'), table_name='compromisso')
    op.drop_table('compromisso')
    op.drop_table('categoria')
    # ### end Alembic commands ###
