"""add discord_link_tokens table

Revision ID: 4526ad6eee2c
Revises: 5b827727960a
Create Date: 2026-03-28 18:53:17.322107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4526ad6eee2c'
down_revision: Union[str, Sequence[str], None] = '5b827727960a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_link_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_link_tokens_discord_id'), 'discord_link_tokens', ['discord_id'], unique=False)
    op.create_index(op.f('ix_discord_link_tokens_id'), 'discord_link_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_discord_link_tokens_token'), 'discord_link_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discord_link_tokens_token'), table_name='discord_link_tokens')
    op.drop_index(op.f('ix_discord_link_tokens_id'), table_name='discord_link_tokens')
    op.drop_index(op.f('ix_discord_link_tokens_discord_id'), table_name='discord_link_tokens')
    op.drop_table('discord_link_tokens')
    # ### end Alembic commands ###
