"""Add saas fields to user

Revision ID: 85b55c95272e
Revises: 40dcc147a7e5
Create Date: 2025-12-22 16:27:21.159447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b55c95272e'
down_revision: Union[str, Sequence[str], None] = '40dcc147a7e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_premium', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('plan_status', sa.String(), nullable=True))
    op.add_column('user', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('discord_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('avatar_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_discord_id'), 'user', ['discord_id'], unique=True)
    op.create_index(op.f('ix_user_stripe_customer_id'), 'user', ['stripe_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stripe_customer_id'), table_name='user')
    op.drop_index(op.f('ix_user_discord_id'), table_name='user')
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'discord_id')
    op.drop_column('user', 'stripe_customer_id')
    op.drop_column('user', 'plan_status')
    op.drop_column('user', 'is_premium')
    # ### end Alembic commands ###
